---

relays:
  hosts:
    relay1:
      ansible_host: relay1
      ansible_ssh_private_key_file: /home/john/.ssh/id_ed25519
      ansible_ssh_port: 22
      ansible_user: john
    relay2:
      ansible_host: relay2
      ansible_ssh_private_key_file: /home/john/.ssh/id_ed25519
      ansible_ssh_port: 22
      ansible_user: john
